Q1. Import numpy as `np` and print the version number.

In [1]:
import numpy as np
print("The Numpy version number is", np.__version__)

The Numpy version number is 1.19.2


Q2. Create a 1D array of numbers from 0 to 9

In [2]:
a=np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Q3. Extract all odd numbers from numpy array

In [3]:
a[a%2!=0]
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

Q4. Replace all odd numbers in array with -1

In [4]:
a = np.random.randint(0,99,10)
for i in range(len(a)):
    if a[i]%2!=0:
        a[i] = -1
a

array([-1, -1, 40, -1, 18,  8, -1, 98, -1, -1])

Q5. Convert a 1D array to a 2D array with 2 rows

In [5]:
a = np.random.randint(0,99,9)
print(a)
a = a.reshape(3,-1)
a

[32 23 86 39 57 77 73 63 36]


array([[32, 23, 86],
       [39, 57, 77],
       [73, 63, 36]])

Q6. Stack the arrays a and b horizontally.

In [6]:
a = np.random.randint(0,99,9)
b = np.random.randint(0,99,9)
c = np.hstack((a,b))
print(a,'\n',b,'\n',c)

[16 72 94 44 21 32 84 28 71] 
 [65 78 80 67 77 16 27 44 95] 
 [16 72 94 44 21 32 84 28 71 65 78 80 67 77 16 27 44 95]


Q7. Get the common items between a and b

In [7]:
li = []
a = np.random.randint(1,15,10)
print(a)
b = np.random.randint(1,15,10)
print(b)
print(a[a==b])

[11 11 14  5 10  9 14 10  6  6]
[ 1  1  2 11  7 10  3  6  4  1]
[]


Q8. From array a remove all items present in array b

In [8]:
li = []
a = np.random.randint(1,15,10)
print(a)
b = np.random.randint(1,15,10)
print(b)
for i in range(len(a)):
    if a[i] in b:
        pass
    else:
        li.append(a[i])
print(li,"item/s not present in array b")

[ 2  8  7  6  9 10  9  8  2  4]
[ 4  5  1  6  6  6  5  1 11  5]
[2, 8, 7, 9, 10, 9, 8, 2] item/s not present in array b


Q9. Get the positions where elements of a and b match

In [9]:
li=[]
a = np.random.randint(1,15,10)
print(a)
b = np.random.randint(1,15,10)
print(b)
print(np.argwhere(a==b))

[12  9 14  3  5 13  7 12  3  5]
[ 9 10  2  4  9  7  9 12  7  7]
[[7]]


Q10. Get all items between 5 and 10 from a.

In [10]:
a = np.random.randint(1,15,10)
print(a)
print(a[5:10])

[ 4  7 14 13  8  1 13 11 10  1]
[ 1 13 11 10  1]


Q11. Swap columns 1 and 2 in the array arr.

In [15]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(np.fliplr(arr))

[[1 2]
 [3 4]]
[[2 1]
 [4 3]]


Q12. Swap rows 1 and 2 in the array arr

In [16]:
arr = np.array([[1,2],[3,4]])
print(arr)
print(np.flipud(arr))

[[1 2]
 [3 4]]
[[3 4]
 [1 2]]
